# Terminal overrides: Cmd+C/V/X need Ctrl+Shift+C/V/X in terminals
[konsole]

mac.c = C-S-c
mac.v = C-S-v
mac.x = C-S-x

# VSCode overrides: Cmd+X/C/V send Ctrl+Shift for clipboard
[code*]

mac.c = C-S-c
mac.x = C-S-x
mac.v = C-S-v

[emacs*]

mac.c = C-S-c
mac.x = C-S-x
